"""Replayed OCR — the CI and development implementation of `OcrPort`.

PaddleOCR needs several hundred megabytes of model weights and a GPU to be tolerable, so CI
cannot run it. Without a substitute, everything downstream of recognition — preprocessing
decisions, confidence scoring, VLM escalation, block assembly, structure detection, the review
editor's payload — would be untested.

This adapter replays recorded page results keyed by the *hash of the page image*. That key is
what makes it a recording rather than a stub: a change anywhere in rasterization or
preprocessing changes the hash, the recording misses, and the test fails loudly instead of
quietly replaying output for an image that no longer exists.

Recordings for the fixture corpus are generated by `kb_idp.testing.make_scans`, which renders
known Vietnamese text and derives the "recognized" lines from that ground truth with the error
modes real scans produce (lost tone marks, speckle, split lines). It is a simulation, and it
says so — it measures the pipeline, never the OCR engine's accuracy.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from kb_common.errors import NotFound
from kb_common.logging import get_logger

from kb_ports.base import AdapterInfo
from kb_ports.models import OcrLine, OcrPageResult
from kb_ports.registry import PortName, register_adapter

log = get_logger(__name__)


def image_key(image: bytes) -> str:
    """Recording key: the page image's content hash, truncated for readability."""
    return hashlib.sha256(image).hexdigest()[:32]


@dataclass
class RecordedOcrAdapter:
    """Replays `{image_key: page_result}` recordings loaded from JSON files."""

    recordings: dict[str, dict[str, Any]] = field(default_factory=dict)
    #: Raise on an unknown image rather than returning an empty page. An empty page looks
    #: like a legitimately blank scan and would be silently accepted.
    strict: bool = True
    misses: list[str] = field(default_factory=list)

    @classmethod
    def from_directory(cls, directory: Path, *, strict: bool = True) -> RecordedOcrAdapter:
        recordings: dict[str, dict[str, Any]] = {}
        for path in sorted(directory.glob("*.ocr.json")):
            recordings.update(json.loads(path.read_text(encoding="utf-8")))
        log.info(
            "ocr_recordings_loaded",
            extra={"directory": str(directory), "pages": len(recordings)},
        )
        return cls(recordings=recordings, strict=strict)

    @property
    def info(self) -> AdapterInfo:
        return AdapterInfo(
            name="recorded",
            version="1",
            extra={
                "real_ocr": False,
                "pages": len(self.recordings),
                "note": "replays recorded pages; measures the pipeline, not OCR accuracy",
            },
        )

    def health(self) -> bool:
        return bool(self.recordings)

    def recognize_page(self, image: bytes, *, page: int = 1) -> OcrPageResult:
        key = image_key(image)
        recording = self.recordings.get(key)
        if recording is None:
            self.misses.append(key)
            if self.strict:
                raise NotFound(
                    "no OCR recording for this page image — regenerate the fixtures if "
                    "rasterization or preprocessing changed",
                    image_key=key,
                    page=page,
                )
            return OcrPageResult(page=page, lines=[], mean_confidence=0.0)

        lines = [
            OcrLine(
                text=line["text"],
                bbox=tuple(float(v) for v in line["bbox"]),  # type: ignore[arg-type]
                confidence=float(line["confidence"]),
            )
            for line in recording.get("lines", [])
        ]
        mean = recording.get("mean_confidence")
        return OcrPageResult(
            page=page,
            lines=lines,
            tables=[
                [list(map(str, row)) for row in table] for table in recording.get("tables", [])
            ],
            layout=list(recording.get("layout", [])),
            mean_confidence=(
                float(mean)
                if mean is not None
                else (sum(line.confidence for line in lines) / len(lines) if lines else 0.0)
            ),
        )


@register_adapter(PortName.OCR, "recorded")
def build_recorded_ocr(directory: Path | str, strict: bool = True) -> RecordedOcrAdapter:
    return RecordedOcrAdapter.from_directory(Path(directory), strict=strict)
